name: Frontend CI

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get Tag Name
        id: vars
        shell: bash
        run: |
          echo ::set-output name=tag_name::$(echo ${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD))
          echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})
      -
        name: Use Node.js 15 to build frontend
        uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
          check-latest: true
      -
        run: yarn
        working-directory: frontend
      -
        run: yarn run build
        working-directory: frontend
        env:
          REACT_APP_VERSION: ${{ github.event.release.tag_name || steps.vars.outputs.tag_name }}
          NODE_ENV: production
      -
        name: Build and push frontend ${{ github.event.release.tag_name || steps.vars.outputs.tag_name }}
        id: docker_build_frontend_tagged_version
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: smartcatboy/aurora-admin-frontend:${{ github.event.release.tag_name || steps.vars.outputs.tag_name }}
      -
        if: github.event_name == 'release'
        name: Build and push frontend latest
        id: docker_build_frontend_latest
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: smartcatboy/aurora-admin-frontend:latest
      -
        if: github.event_name != 'release'
        name: Build and push frontend dev latest
        id: docker_build_frontend_test_latest
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: smartcatboy/aurora-admin-frontend:${{ steps.vars.outputs.branch }}-latest
      -
        name: Frontend digest
        run: echo ${{ steps.docker_build_frontend_tagged_version.outputs.digest }}
